remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme

title: Khoa Pham
logo: /images/My Portrait.png
description: 714-858-7494 | kdpham@umass.edu | Los Angeles, CA
show_downloads: true
theme: jekyll-theme-minimal
