remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme

title: Khoa Pham
logo: /assets/img/My Portrait.jpg
description:
  - 📍 Based in Los Angeles, CA
  - 💌 kdpham1002@gmail.com (Personal)
  - 📧 kdpham@umass.edu (School)
  - 📞 (714) 858-7494
  -
  - 🎓 I'm a Master's student majoring in Data Science and Business Analytics.
  - 📊 I'm passionate about using data to uncover insights and support strategic decision-making.
  - 📈 My experience in finance and healthcare has helped me enhance data analysis and research skills.
  - 🧑‍💻 Proficient in Python, SQL, R, and Tableau, and currently advancing my skills in Data Engineering and Cloud technologies.

# show_downloads: true
theme: jekyll-theme-minimal