remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme

title: Khoa Pham
logo: /assets/img/My Portrait.jpg
description:
  - 📍 Based in Los Angeles, CA
  - 💌 kdpham1002@gmail.com (Personal)
  - 📧 kdpham@umass.edu (School)
  - 📞 (714) 858-7494
  -
  - 🎓 I'm a Master's student majoring in Data Science and Business Analytics.
  - 📊 I'm passionate about using data to drive insights and support decision-making.
  - 📈 My experiences in finance, healthcare refined my data analysis and research skills.
  - 🧑‍💻 Skilled in Python, SQL, R, Tableau but I'm also learning Data Engineering skills and Cloud technologies.

# show_downloads: true
theme: jekyll-theme-minimal