remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme

title: Khoa Pham
logo: /assets/img/My Portrait.jpg
description:
  - kdpham1002@gmail.com (Personal)
  - Los Angeles, CA
  -
  - • I am a Masters student with Data Science and Business Analyst major
  - • Skilled in Python, SQL, R, and Tableau. I'm learning Data Engineering/Big Data skills.
  - • I have experiences in finance, mental health research, and web programming projects.
  - • My roles as a Data Assistant and Research Assistant have refined my data analysis and communication skills.
  - • I am passionate about using data to drive insights and support decision-making.
# show_downloads: true
theme: jekyll-theme-minimal