remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme

title: Khoa Pham
logo: /assets/My Portrait.png
description:
  - kdpham1002@gmail.com (Personal)
  - 714-858-7494 (Phone Number)

# show_downloads: true
theme: jekyll-theme-minimal
