remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme

title: Khoa Pham
logo: /images/My Portrait.png
description: All Data Science Projects go here!
url: https://khoapham.github.io/DS_portfolio/
url2: https://khoapham.github.io/DS_portfolio/
# show_downloads: true
theme: jekyll-theme-minimal
