remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme

title: Khoa Pham
logo: /images/My Portrait.png
description: kdpham1002@gmail.com (Personal)
show_downloads: true
theme: jekyll-theme-minimal
