remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme

title: Khoa Pham
logo: /assets/img/My Portrait_small.png
# description: text below image
# show_downloads: true
theme: jekyll-theme-minimal